<?php


use VendorClassCuatro\ModuloClassCuatro\Block\CustomMessage;

/** @var CustomMessage $block */
?>

<div class="custom-message">
    <h4><?= $block->getCustomMessage() ?></h4>
</div>


<!-- ¿Qué hace esta Template?

- Esta template usa el método getCustomeMessage() del bloque CustomMessage para obtener el mensaje.
- Renderiza el mensae ne un contendor HTML div con la clase custom-message.


-->
